[project]
name = "nesi-agent"
version = "0.1.0"
description = "NESI negotiation agent implemented for CSE3210 HCI."
authors = [
    {name = "Emilio Gennaro", email = "e.s.gennarocostanza@student.tudelft.nl"}
]
readme = "README.md"
requires-python = ">=3.7"
license = {text = "MIT"}

[project.dependencies]
negmas = "*"
pytest = {version = "*", optional = false}

[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"
